name: Run E2E tests
description: Run the E2E tests against an environment

inputs:
  e2e_test_token:
    description: The authentication token used for E2E test endpoints.
    required: true
  slack_token:
    description: The slack authentication token.
    required: true
  environment:
    description: The value of the ENV environment variable to use for npm run env.
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version-file: frontend/.nvmrc
        cache-dependency-path: frontend/package-lock.json

    - name: NPM Install
      working-directory: frontend
      run: |
        npm ci
      shell: bash

    - name: Test with Chromedriver
      working-directory: frontend
      env:
        E2E_TEST_TOKEN: ${{ inputs.e2e_test_token }}
        SLACK_TOKEN: ${{ inputs.slack_token }}
        STATIC_ASSET_CDN_URL: /
        ENV: ${{ inputs.environment }}

      run: |
        node -v
        npm run env
        npm run test
      shell: bash
