name: Frontend Audit

on:
  schedule:
    - cron: 0 8 * * *

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Audit
        working-directory: frontend
        run: |
          npm ci
          npm audit --audit-level high
