name: Staging E2E Tests

on: workflow_dispatch

jobs:
  run-staging-e2e-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Full Staging E2E tests
    environment: staging

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Staging E2E Tests
        working-directory: frontend
        env:
          E2E_TEST_TOKEN_STAGING: ${{ secrets.E2E_TEST_TOKEN }}
          ENV: staging
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STATIC_ASSET_CDN_URL: /
        run: |-
          wget -q ${{ secrets.CHROME_URL }}
          sudo apt install --allow-downgrades -y ./google-chrome*.deb -f
          google-chrome --version
          node -v
          npm ci
          npm run test:staging
