name: Frontend Deploy to Vercel Staging

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/**

defaults:
  run:
    working-directory: frontend

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to Vercel Staging
    environment: staging

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Deploy to Vercel
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          ENV: staging
        run: |
          npm ci --only=prod
          npm run env
          npm run bundle
          echo ${{ github.sha }} > CI_COMMIT_SHA
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
