name: Platform Test Merge to Main

on:
  push:
    branches:
      - main

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    name: Full E2E tests

    services:
      postgres:
        image: postgres:11.12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flagsmith
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Local API
        id: run-local-api
        uses: ./.github/actions/run-local-api
        with:
          e2e_test_token: some-token
          # As per https://stackoverflow.com/q/65497331/421808 172.17.0.1 seems like the only way to resolve host DB
          database_url: postgres://postgres:postgres@172.17.0.1:5432/flagsmith
          sentry_sdk_dsn: ${{ secrets.SENTRY_SDK_DSN }}
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          disable_analytics_features: true

      - name: Run E2E tests against local
        uses: ./.github/actions/e2e-tests
        with:
          e2e_test_token: some-token
          slack_token: ${{ secrets.SLACK_TOKEN }}
          environment: local

      - name: Output API logs
        if: failure()
        env:
          API_CONTAINER_ID: ${{ steps.run-local-api.outputs.containerId }}
        run: docker logs $API_CONTAINER_ID
